### ISSUE TITLE
Improve Vagrant Documentation

### ISSUE THREAD

**Issue by lbogaardt** [nlesc-sherlock/emma#71]
- [ ] 1. Note to run Bash as Administrator in Windows, otherwise VAGRANT_HOME is not writable
- [x] 2. Explain that `VirtualBox` is required
- [x] 3. Explain that the `.exe` is necessary for Windows user, or that they should make an alias `vagrant=vagrant.exe`
- [ ] 4. Note that `export PATH=$PATH:/mnt/c/Windows/System32/` is required
- [x] 5. Line `ssh -i pheno.key root@pheno0.$HOST_DOMAIN uptime` > should be ` ssh -i ${HOST_NAME}.key root@${HOST_NAME}0.${HOST_DOMAIN} uptime`
- [x] 6. Line `POSIX user ${HOST_NAME}` > wrong .yml file

**Comment by romulogoncalves** [comment]
Items not solved:
1. Does not seem to be an issue since Ubuntu bash on windows mounts all drivers with all permissions on.

4. In the general documentation we ask the use to add it to the PATH using ~/.bashrc

The remain ones were solved by:
9165c5a99518e4d585c0f8986497856d0ff173de
9df385db41168b7ddc4110cdcdae1814b9f11059

**Comment by romulogoncalves** [comment]
Changes were merger into the master by:
https://github.com/nlesc-sherlock/emma/pull/73
